version: '3'
services:
  yukx-eureka:
    restart: always   # 重启方式
    image: "yukx-eureka:1.0"  # 镜像名称
    container_name: yukx-eureka # 容器名称
    hostname: localhost
    ports:
      - 8762:8762
    build:
      ./yukx_eureka
    networks:
      - app-network
#    volumes:
#      - ./log:/data/logs
  yukx-config:
    container_name: yukx-config
    image: "yukx-config:1.0"
    networks:       # 接入网路1
      - app-network
    depends_on:
      - yukx-eureka
    ports:
      - 9002:9002   # 端口映射
#    links:
#      - yukx-eureka    所有服务接入同一网络，不需要links了
    build:    # 没有镜像时从一下目录构建
      ./yukx_config
#    volumes:  # 日志挂载
#      - ./log:/data/logs
    healthcheck:    # 添加健康检查，需要提供检查接口，返回0表示正常
      test: ["CMD","curl","-f", "http://localhost:9002/health/doCheck"]
      interval: 30s
      timeout: 10s
      retries: 5
  yukx-mysql:
    restart: always
    image: mysql:5.7.24
    container_name: yukx-mysql
    networks:
      - app-network
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: yukx
    volumes:
      - /Users/yukx/Documents/soft/mysqldb:/var/lib/mysql
  yukx-redis:
    restart: always
    image: redis:4.0.12
    container_name: yukx-redis
    command: redis-server --requirepass "123456"
    networks:
      - app-network
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/yukx/Documents/soft/docker_volume/redis:/data
  yukx-auth:
    container_name: yukx-auth
    image: "yukx-auth:1.0"
    networks:
      - app-network
    depends_on:
      yukx-config:
        condition: service_healthy  # 健康检查，检查成功后才会启动本服务
    ports:
      - 9020:9020
    build:
      ./yukx_auth
#    volumes:
#      - ./log:/data/logs
  yukx-service:
    container_name: yukx-service
    image: "yukx-service:1.0"
    networks:
      - app-network
    depends_on:
      yukx-config:
        condition: service_healthy
    ports:
      - 9010:9010
    build:
      ./yukx_service
#    volumes:
#      - ./log:/data/logs
  yukx-user:
    container_name: yukx-user
    image: "yukx-user:1.0"
    networks:
      - app-network
    depends_on:
      yukx-config:
        condition: service_healthy
    ports:
      - 9040:9040
    build:
      ./yukx_user
#    volumes:
#      - ./log:/data/logs
  yukx-gateway:
    container_name: yukx-gateway
    image: "yukx-gateway:1.0"
    networks:
      - app-network
    depends_on:
      yukx-config:
        condition: service_healthy
    ports:
      - 9030:9030
    build:
      ./yukx_gateway
#    volumes:
#      - ./log:/data/logs
networks:
  app-network:
    driver: bridge #以桥接模式创建自定义网络，否则会使用默认的网络
