version: '3'
services:
  yukx-eureka:
    restart: always   # 重启方式
    image: "yukx-eureka:1.0"  # 镜像名称
    container_name: yukx-eureka # 容器名称
    hostname: localhost
    command: --spring.profiles.active=test
    ports:
      - 8762:8762
    build:
      ./yukx_eureka
    networks:
      - app-network
  yukx-config:
    container_name: yukx-config
    image: "yukx-config:1.0"
    hostname: yukx_eureka
    networks:
      - app-network
    depends_on:
      - yukx-eureka
    ports:
      - 9002:9002
    command: --spring.profiles.active=test
    links:
      - yukx-eureka
    build:
      ./yukx_config
networks:
  app-network:
    driver: bridge #以桥接模式创建自定义网络，否则会使用默认的网络
