server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  serviceUrl:
    defnce.hostname}:${server.port}/eureka/aultZone: http://yukx:123456@localhost:8761/eureka= http://${eureka.insta