server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册到Eureka Server
    fetch-registry: false # 表示是否从Eureka Server获取注册信息
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://yukx:123456@localhost:8761/eureka= http://${eureka.instance.hostname}:${server.port}/eureka/