server:
  port: 8763
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://yukx:123456@localhost:8761/eureka= http://${eureka.instance.hostname}:${server.port}/eureka/