server:
  port: 9001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yukxx/config-repe.git
          username: ykx694883436@gmail.com
          password: ykxyj1314.
eureka:
  client:
    service-url:
      defaultZone: http://yukx:123456@localhost:8761/eureka
    server:
      enable-self-preservation: true
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长