server:
  port: 9001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yukxx/oauthConfig.git
          username: ykx694883436@gmail.com
          password: ykxyj1314.
          search-paths: oauthConfig # 检索git指定目录下面的文件， 可以逗号区分、模糊匹配等,临时存放在系统的位置，注意在日志中查看
eureka:
  client:
    service-url:
      defaultZone: http://yukx:123456@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长